{"ast":null,"code":"import axios from 'axios';\nconst apiUrl = \"http://localhost:5221/items\";\naxios.defaults.baseURL = \"http://localhost:5221/items\";\naxios.interceptors.response.use(function (response) {\n  // Any status code that lie within the range of 2xx cause this function to trigger\n  // Do something with response data\n  return response;\n}, function (error) {\n  // Any status codes that falls outside the range of 2xx cause this function to trigger\n  // Do something with response error\n  return Promise.reject(error);\n});\nexport default {\n  getTasks: async item => {\n    // const result = await axios.get(`${apiUrl}`)    \n    // return result.data;\n    const result = await axios.get();\n    return result.data;\n  },\n  addTask: async name => {\n    var item = {\n      Id: 0,\n      Name: name,\n      IsComplete: false\n    };\n    await axios.post('', item);\n    console.log('addTask', item);\n    //TODO\n    return {};\n  },\n  setCompleted: async (id, isComplete) => {\n    await axios.put(`/${id}`, {\n      IsComplete: isComplete\n    });\n    console.log('setCompleted', {\n      id,\n      isComplete\n    });\n    //TODO\n    return {};\n  },\n  deleteTask: async id => {\n    await axios.delete(`/${id}`);\n    console.log('deleteTask');\n  }\n};","map":{"version":3,"names":["axios","apiUrl","defaults","baseURL","interceptors","response","use","error","Promise","reject","getTasks","item","result","get","data","addTask","name","Id","Name","IsComplete","post","console","log","setCompleted","id","isComplete","put","deleteTask","delete"],"sources":["C:/Users/user/Desktop/פרקטיקוד/ToDoListReact-master/src/service.js"],"sourcesContent":["import axios from 'axios';\n\nconst apiUrl = \"http://localhost:5221/items\"\naxios.defaults.baseURL= \"http://localhost:5221/items\"\naxios.interceptors.response.use(function (response) {\n  \n  // Any status code that lie within the range of 2xx cause this function to trigger\n  // Do something with response data\n  return response;\n}, function (error) {\n  // Any status codes that falls outside the range of 2xx cause this function to trigger\n  // Do something with response error\n  return Promise.reject(error);\n});\n\nexport default {\n  getTasks: async (item) => {\n    // const result = await axios.get(`${apiUrl}`)    \n    // return result.data;\n    const result = await axios.get()    \n    return result.data;\n  },\n\n  addTask: async(name)=>{\n    var item={Id:0,Name:name,IsComplete:false}\n    await axios.post('',item)\n    console.log('addTask', item)\n    //TODO\n    return {};\n  },\n\n  setCompleted: async(id, isComplete)=>{\n    await axios.put(`/${id}`,{IsComplete:isComplete})\n    console.log('setCompleted', {id, isComplete})\n    //TODO\n    return {};\n  },\n\n  deleteTask:async(id)=>{\n    await axios.delete(`/${id}`)\n    console.log('deleteTask')\n  }\n};\n"],"mappings":"AAAA,OAAOA,KAAK,MAAM,OAAO;AAEzB,MAAMC,MAAM,GAAG,6BAA6B;AAC5CD,KAAK,CAACE,QAAQ,CAACC,OAAO,GAAE,6BAA6B;AACrDH,KAAK,CAACI,YAAY,CAACC,QAAQ,CAACC,GAAG,CAAC,UAAUD,QAAQ,EAAE;EAElD;EACA;EACA,OAAOA,QAAQ;AACjB,CAAC,EAAE,UAAUE,KAAK,EAAE;EAClB;EACA;EACA,OAAOC,OAAO,CAACC,MAAM,CAACF,KAAK,CAAC;AAC9B,CAAC,CAAC;AAEF,eAAe;EACbG,QAAQ,EAAE,MAAOC,IAAI,IAAK;IACxB;IACA;IACA,MAAMC,MAAM,GAAG,MAAMZ,KAAK,CAACa,GAAG,EAAE;IAChC,OAAOD,MAAM,CAACE,IAAI;EACpB,CAAC;EAEDC,OAAO,EAAE,MAAMC,IAAI,IAAG;IACpB,IAAIL,IAAI,GAAC;MAACM,EAAE,EAAC,CAAC;MAACC,IAAI,EAACF,IAAI;MAACG,UAAU,EAAC;IAAK,CAAC;IAC1C,MAAMnB,KAAK,CAACoB,IAAI,CAAC,EAAE,EAACT,IAAI,CAAC;IACzBU,OAAO,CAACC,GAAG,CAAC,SAAS,EAAEX,IAAI,CAAC;IAC5B;IACA,OAAO,CAAC,CAAC;EACX,CAAC;EAEDY,YAAY,EAAE,MAAAA,CAAMC,EAAE,EAAEC,UAAU,KAAG;IACnC,MAAMzB,KAAK,CAAC0B,GAAG,CAAE,IAAGF,EAAG,EAAC,EAAC;MAACL,UAAU,EAACM;IAAU,CAAC,CAAC;IACjDJ,OAAO,CAACC,GAAG,CAAC,cAAc,EAAE;MAACE,EAAE;MAAEC;IAAU,CAAC,CAAC;IAC7C;IACA,OAAO,CAAC,CAAC;EACX,CAAC;EAEDE,UAAU,EAAC,MAAMH,EAAE,IAAG;IACpB,MAAMxB,KAAK,CAAC4B,MAAM,CAAE,IAAGJ,EAAG,EAAC,CAAC;IAC5BH,OAAO,CAACC,GAAG,CAAC,YAAY,CAAC;EAC3B;AACF,CAAC"},"metadata":{},"sourceType":"module"}